#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [[ "${CODESPACES:-}" == 'true' ]]; then
  apt install -y \
    vim
fi

if [[ $(uname) == 'Darwin' ]] ; then
  brew tap homebrew/bundle
  brew tap homebrew/cask
  brew tap homebrew/core
  brew tap homeport/tap
  brew tap lacework/tap
  brew tap puppetlabs/puppet
  brew tap stripe/stripe-cli
  brew tap snyk/tap
  brew tap turbot/tap
  brew install \
    ansible \
    autoconf \
    aws-iam-authenticator \
    awscli \
    colordiff \
    coreutils \
    cmake \
    container-diff \
    ctags \
    exercism \
    eksctl \
    dive \
    dyff \
    fzf \
    findutils \
    gh \
    go \
    go@1.14 \
    gosec \
    git \
    gnu-getopt \
    gnu-sed \
    gnuplot \
    gnutls \
    helm \
    jfrog-cli \
    jq \
    jsonnet \
    kubernetes-cli \
    kubeval \
    kustomize \
    lacework-cli \
    lego \
    lua \
    packer \
    perl \
    pipenv \
    pstree \
    rbenv \
    readline \
    saml2aws \
    shellcheck \
    steampipe \
    telnet \
    terraform \
    terraform-docs \
    terraform@0.13 \
    terragrunt \
    terrascan \
    tflint \
    the_silver_searcher \
    tmux \
    vale \
    vim \
    wget \
    ncurses \
    nmap \
    xz \
    imath \
    yq
fi
